validator="../../Build_CI/iab-validator"
output_path="../out/cA/"
input_path="../bitstreams/"


${validator} -i${input_path}/IABValidationStream_1.iab -cA -s -r1 -o${output_path}Stream1_cA.json
${validator} -i${input_path}/IABValidationStream_2.iab -cA -s -r1 -o${output_path}Stream2_cA.json
${validator} -i${input_path}/IABValidationStream_3.iab -cA -s -r1 -o${output_path}Stream3_cA.json
${validator} -i${input_path}/IABValidationStream_4.iab -cA -s -r1 -o${output_path}Stream4_cA.json
${validator} -i${input_path}/IABValidationStream_5.iab -cA -s -r1 -o${output_path}Stream5_cA.json
${validator} -i${input_path}/IABValidationStream_6.iab -cA -s -r1 -o${output_path}Stream6_cA.json
${validator} -i${input_path}/IABValidationStream_7.iab -cA -s -r1 -o${output_path}Stream7_cA.json
${validator} -i${input_path}/IABValidationStream_8.iab -cA -s -r1 -o${output_path}Stream8_cA.json
${validator} -i${input_path}/IABValidationStream_9.iab -cA -s -r1 -o${output_path}Stream9_cA.json
${validator} -i${input_path}/IABValidationStream_10.iab -cA -s -r1 -o${output_path}Stream10_cA.json
${validator} -i${input_path}/IABValidationStream_11.iab -cA -s -r1 -o${output_path}Stream11_cA.json
${validator} -i${input_path}/IABValidationStream_12.iab -cA -s -r1 -o${output_path}Stream12_cA.json
${validator} -i${input_path}/IABValidationStream_13.iab -cA -s -r1 -o${output_path}Stream13_cA.json
${validator} -i${input_path}/IABValidationStream_14.iab -cA -s -r1 -o${output_path}Stream14_cA.json
${validator} -i${input_path}/IABValidationStream_15.iab -cA -s -r1 -o${output_path}Stream15_cA.json
${validator} -i${input_path}/IABValidationStream_16.iab -cA -s -r1 -o${output_path}Stream16_cA.json
${validator} -i${input_path}/IABValidationStream_17.iab -cA -s -r1 -o${output_path}Stream17_cA.json
${validator} -i${input_path}/IABValidationStream_18.iab -cA -s -r1 -o${output_path}Stream18_cA.json
${validator} -i${input_path}/IABValidationStream_19.iab -cA -s -r1 -o${output_path}Stream19_cA.json
${validator} -i${input_path}/IABValidationStream_20.iab -cA -s -r1 -o${output_path}Stream20_cA.json
${validator} -i${input_path}/IABValidationStream_21.iab -cA -s -r1 -o${output_path}Stream21_cA.json
${validator} -i${input_path}/IABValidationStream_22.iab -cA -s -r1 -o${output_path}Stream22_cA.json
${validator} -i${input_path}/IABValidationStream_23.iab -cA -s -r1 -o${output_path}Stream23_cA.json
${validator} -i${input_path}/IABValidationStream_24.iab -cA -s -r1 -o${output_path}Stream24_cA.json
${validator} -i${input_path}/IABValidationStream_25.iab -cA -s -r1 -o${output_path}Stream25_cA.json
${validator} -i${input_path}/IABValidationStream_26.iab -cA -s -r1 -o${output_path}Stream26_cA.json
${validator} -i${input_path}/IABValidationStream_27.iab -cA -s -r1 -o${output_path}Stream27_cA.json
${validator} -i${input_path}/IABValidationStream_28.iab -cA -s -r1 -o${output_path}Stream28_cA.json
${validator} -i${input_path}/IABValidationStream_29.iab -cA -s -r1 -o${output_path}Stream29_cA.json
${validator} -i${input_path}/IABValidationStream_30.iab -cA -s -r1 -o${output_path}Stream30_cA.json
${validator} -i${input_path}/IABValidationStream_31.iab -cA -s -r1 -o${output_path}Stream31_cA.json
${validator} -i${input_path}/IABValidationStream_32.iab -cA -s -r1 -o${output_path}Stream32_cA.json
${validator} -i${input_path}/IABValidationStream_33.iab -cA -s -r1 -o${output_path}Stream33_cA.json
${validator} -i${input_path}/IABValidationStream_34.iab -cA -s -r1 -o${output_path}Stream34_cA.json
${validator} -i${input_path}/IABValidationStream_35.iab -cA -s -r1 -o${output_path}Stream35_cA.json
${validator} -i${input_path}/IABValidationStream_36.iab -cA -s -r1 -o${output_path}Stream36_cA.json
${validator} -i${input_path}/IABValidationStream_37.iab -cA -s -r1 -o${output_path}Stream37_cA.json
${validator} -i${input_path}/IABValidationStream_38.iab -cA -s -r1 -o${output_path}Stream38_cA.json
${validator} -i${input_path}/IABValidationStream_39.iab -cA -s -r1 -o${output_path}Stream39_cA.json
${validator} -i${input_path}/IABValidationStream_40.iab -cA -s -r1 -o${output_path}Stream40_cA.json
${validator} -i${input_path}/IABValidationStream_41.iab -cA -s -r1 -o${output_path}Stream41_cA.json
${validator} -i${input_path}/IABValidationStream_42.iab -cA -s -r1 -o${output_path}Stream42_cA.json
${validator} -i${input_path}/IABValidationStream_43.iab -cA -s -r1 -o${output_path}Stream43_cA.json
${validator} -i${input_path}/IABValidationStream_44.iab -cA -s -r1 -o${output_path}Stream44_cA.json
${validator} -i${input_path}/IABValidationStream_45.iab -cA -s -r1 -o${output_path}Stream45_cA.json
${validator} -i${input_path}/IABValidationStream_46.iab -cA -s -r1 -o${output_path}Stream46_cA.json
${validator} -i${input_path}/IABValidationStream_47.iab -cA -s -r1 -o${output_path}Stream47_cA.json
${validator} -i${input_path}/IABValidationStream_48.iab -cA -s -r1 -o${output_path}Stream48_cA.json
${validator} -i${input_path}/IABValidationStream_49.iab -cA -s -r1 -o${output_path}Stream49_cA.json
${validator} -i${input_path}/IABValidationStream_50.iab -cA -s -r1 -o${output_path}Stream50_cA.json
${validator} -i${input_path}/IABValidationStream_51.iab -cA -s -r1 -o${output_path}Stream51_cA.json
${validator} -i${input_path}/IABValidationStream_52.iab -cA -s -r1 -o${output_path}Stream52_cA.json
${validator} -i${input_path}/IABValidationStream_53.iab -cA -s -r1 -o${output_path}Stream53_cA.json
${validator} -i${input_path}/IABValidationStream_54.iab -cA -s -r1 -o${output_path}Stream54_cA.json
${validator} -i${input_path}/IABValidationStream_55.iab -cA -s -r1 -o${output_path}Stream55_cA.json
${validator} -i${input_path}/IABValidationStream_56.iab -cA -s -r1 -o${output_path}Stream56_cA.json
${validator} -i${input_path}/IABValidationStream_57.iab -cA -s -r1 -o${output_path}Stream57_cA.json
${validator} -i${input_path}/IABValidationStream_58.iab -cA -s -r1 -o${output_path}Stream58_cA.json
${validator} -i${input_path}/IABValidationStream_59.iab -cA -s -r1 -o${output_path}Stream59_cA.json
${validator} -i${input_path}/IABValidationStream_60.iab -cA -s -r1 -o${output_path}Stream60_cA.json
${validator} -i${input_path}/IABValidationStream_61.iab -cA -s -r1 -o${output_path}Stream61_cA.json
${validator} -i${input_path}/IABValidationStream_62.iab -cA -s -r1 -o${output_path}Stream62_cA.json
${validator} -i${input_path}/IABValidationStream_63.iab -cA -s -r1 -o${output_path}Stream63_cA.json
${validator} -i${input_path}/IABValidationStream_64.iab -cA -s -r1 -o${output_path}Stream64_cA.json
${validator} -i${input_path}/IABValidationStream_65.iab -cA -s -r1 -o${output_path}Stream65_cA.json
${validator} -i${input_path}/IABValidationStream_66.iab -cA -s -r1 -o${output_path}Stream66_cA.json
${validator} -i${input_path}/IABValidationStream_67.iab -cA -s -r1 -o${output_path}Stream67_cA.json
${validator} -i${input_path}/IABValidationStream_68.iab -cA -s -r1 -o${output_path}Stream68_cA.json
${validator} -i${input_path}/IABValidationStream_69.iab -cA -s -r1 -o${output_path}Stream69_cA.json
${validator} -i${input_path}/IABValidationStream_70.iab -cA -s -r1 -o${output_path}Stream70_cA.json
${validator} -i${input_path}/IABValidationStream_71.iab -cA -s -r1 -o${output_path}Stream71_cA.json
${validator} -i${input_path}/IABValidationStream_72.iab -cA -s -r1 -o${output_path}Stream72_cA.json
${validator} -i${input_path}/IABValidationStream_73.iab -cA -s -r1 -o${output_path}Stream73_cA.json
${validator} -i${input_path}/IABValidationStream_74.iab -cA -s -r1 -o${output_path}Stream74_cA.json
${validator} -i${input_path}/IABValidationStream_75.iab -cA -s -r1 -o${output_path}Stream75_cA.json
${validator} -i${input_path}/IABValidationStream_76.iab -cA -s -r1 -o${output_path}Stream76_cA.json
${validator} -i${input_path}/IABValidationStream_77.iab -cA -s -r1 -o${output_path}Stream77_cA.json
${validator} -i${input_path}/IABValidationStream_78.iab -cA -s -r1 -o${output_path}Stream78_cA.json
${validator} -i${input_path}/IABValidationStream_79.iab -cA -s -r1 -o${output_path}Stream79_cA.json
${validator} -i${input_path}/IABValidationStream_80.iab -cA -s -r1 -o${output_path}Stream80_cA.json
${validator} -i${input_path}/IABValidationStream_81.iab -cA -s -r1 -o${output_path}Stream81_cA.json
${validator} -i${input_path}/IABValidationStream_82.iab -cA -s -r1 -o${output_path}Stream82_cA.json
${validator} -i${input_path}/IABValidationStream_83.iab -cA -s -r1 -o${output_path}Stream83_cA.json
${validator} -i${input_path}/IABValidationStream_84.iab -cA -s -r1 -o${output_path}Stream84_cA.json
${validator} -i${input_path}/IABValidationStream_85.iab -cA -s -r1 -o${output_path}Stream85_cA.json
${validator} -i${input_path}/IABValidationStream_86.iab -cA -s -r1 -o${output_path}Stream86_cA.json
${validator} -i${input_path}/IABValidationStream_87.iab -cA -s -r1 -o${output_path}Stream87_cA.json
${validator} -i${input_path}/IABValidationStream_88.iab -cA -s -r1 -o${output_path}Stream88_cA.json
${validator} -i${input_path}/IABValidationStream_89.iab -cA -s -r1 -o${output_path}Stream89_cA.json
${validator} -i${input_path}/IABValidationStream_90.iab -cA -s -r1 -o${output_path}Stream90_cA.json
${validator} -i${input_path}/IABValidationStream_91.iab -cA -s -r1 -o${output_path}Stream91_cA.json
${validator} -i${input_path}/IABValidationStream_92.iab -cA -s -r1 -o${output_path}Stream92_cA.json
${validator} -i${input_path}/IABValidationStream_93.iab -cA -s -r1 -o${output_path}Stream93_cA.json
${validator} -i${input_path}/IABValidationStream_94.iab -cA -s -r1 -o${output_path}Stream94_cA.json
${validator} -i${input_path}/IABValidationStream_95.iab -cA -s -r1 -o${output_path}Stream95_cA.json
${validator} -i${input_path}/IABValidationStream_96.iab -cA -s -r1 -o${output_path}Stream96_cA.json
${validator} -i${input_path}/IABValidationStream_97.iab -cA -s -r1 -o${output_path}Stream97_cA.json
${validator} -i${input_path}/IABValidationStream_98.iab -cA -s -r1 -o${output_path}Stream98_cA.json
${validator} -i${input_path}/IABValidationStream_99.iab -cA -s -r1 -o${output_path}Stream99_cA.json
${validator} -i${input_path}/IABValidationStream_100.iab -cA -s -r1 -o${output_path}Stream100_cA.json
${validator} -i${input_path}/IABValidationStream_101.iab -cA -s -r1 -o${output_path}Stream101_cA.json
${validator} -i${input_path}/IABValidationStream_102.iab -cA -s -r1 -o${output_path}Stream102_cA.json
${validator} -i${input_path}/IABValidationStream_103.iab -cA -s -r1 -o${output_path}Stream103_cA.json
${validator} -i${input_path}/IABValidationStream_104.iab -cA -s -r1 -o${output_path}Stream104_cA.json
${validator} -i${input_path}/IABValidationStream_105.iab -cA -s -r1 -o${output_path}Stream105_cA.json
${validator} -i${input_path}/IABValidationStream_106.iab -cA -s -r1 -o${output_path}Stream106_cA.json
${validator} -i${input_path}/IABValidationStream_107.iab -cA -s -r1 -o${output_path}Stream107_cA.json
${validator} -i${input_path}/IABValidationStream_108.iab -cA -s -r1 -o${output_path}Stream108_cA.json
${validator} -i${input_path}/IABValidationStream_109.iab -cA -s -r1 -o${output_path}Stream109_cA.json
${validator} -i${input_path}/IABValidationStream_110.iab -cA -s -r1 -o${output_path}Stream110_cA.json
${validator} -i${input_path}/IABValidationStream_111.iab -cA -s -r1 -o${output_path}Stream111_cA.json
${validator} -i${input_path}/IABValidationStream_112.iab -cA -s -r1 -o${output_path}Stream112_cA.json
${validator} -i${input_path}/IABValidationStream_113.iab -cA -s -r1 -o${output_path}Stream113_cA.json
${validator} -i${input_path}/IABValidationStream_114.iab -cA -s -r1 -o${output_path}Stream114_cA.json
${validator} -i${input_path}/IABValidationStream_115.iab -cA -s -r1 -o${output_path}Stream115_cA.json
${validator} -i${input_path}/IABValidationStream_116.iab -cA -s -r1 -o${output_path}Stream116_cA.json
${validator} -i${input_path}/IABValidationStream_117.iab -cA -s -r1 -o${output_path}Stream117_cA.json
${validator} -i${input_path}/IABValidationStream_118.iab -cA -s -r1 -o${output_path}Stream118_cA.json
${validator} -i${input_path}/IABValidationStream_119.iab -cA -s -r1 -o${output_path}Stream119_cA.json
${validator} -i${input_path}/IABValidationStream_120.iab -cA -s -r1 -o${output_path}Stream120_cA.json
${validator} -i${input_path}/IABValidationStream_121.iab -cA -s -r1 -o${output_path}Stream121_cA.json
${validator} -i${input_path}/IABValidationStream_122.iab -cA -s -r1 -o${output_path}Stream122_cA.json
${validator} -i${input_path}/IABValidationStream_123.iab -cA -s -r1 -o${output_path}Stream123_cA.json
${validator} -i${input_path}/IABValidationStream_124.iab -cA -s -r1 -o${output_path}Stream124_cA.json
${validator} -i${input_path}/IABValidationStream_125.iab -cA -s -r1 -o${output_path}Stream125_cA.json
${validator} -i${input_path}/IABValidationStream_126.iab -cA -s -r1 -o${output_path}Stream126_cA.json
${validator} -i${input_path}/IABValidationStream_127.iab -cA -s -r1 -o${output_path}Stream127_cA.json
${validator} -i${input_path}/IABValidationStream_128.iab -cA -s -r1 -o${output_path}Stream128_cA.json
${validator} -i${input_path}/IABValidationStream_129.iab -cA -s -r1 -o${output_path}Stream129_cA.json
${validator} -i${input_path}/IABValidationStream_130.iab -cA -s -r1 -o${output_path}Stream130_cA.json
${validator} -i${input_path}/IABValidationStream_131.iab -cA -s -r1 -o${output_path}Stream131_cA.json
${validator} -i${input_path}/IABValidationStream_132.iab -cA -s -r1 -o${output_path}Stream132_cA.json
${validator} -i${input_path}/IABValidationStream_133.iab -cA -s -r1 -o${output_path}Stream133_cA.json
${validator} -i${input_path}/IABValidationStream_134.iab -cA -s -r1 -o${output_path}Stream134_cA.json
${validator} -i${input_path}/IABValidationStream_135.iab -cA -s -r1 -o${output_path}Stream135_cA.json
${validator} -i${input_path}/IABValidationStream_136.iab -cA -s -r1 -o${output_path}Stream136_cA.json
${validator} -i${input_path}/IABValidationStream_137.iab -cA -s -r1 -o${output_path}Stream137_cA.json
${validator} -i${input_path}/IABValidationStream_138.iab -cA -s -r1 -o${output_path}Stream138_cA.json
${validator} -i${input_path}/IABValidationStream_139.iab -cA -s -r1 -o${output_path}Stream139_cA.json
${validator} -i${input_path}/IABValidationStream_140.iab -cA -s -r1 -o${output_path}Stream140_cA.json
${validator} -i${input_path}/IABValidationStream_141.iab -cA -s -r1 -o${output_path}Stream141_cA.json
${validator} -i${input_path}/IABValidationStream_142.iab -cA -s -r1 -o${output_path}Stream142_cA.json
${validator} -i${input_path}/IABValidationStream_143.iab -cA -s -r1 -o${output_path}Stream143_cA.json
${validator} -i${input_path}/IABValidationStream_144.iab -cA -s -r1 -o${output_path}Stream144_cA.json
${validator} -i${input_path}/IABValidationStream_145.iab -cA -s -r1 -o${output_path}Stream145_cA.json
${validator} -i${input_path}/IABValidationStream_146.iab -cA -s -r1 -o${output_path}Stream146_cA.json
${validator} -i${input_path}/IABValidationStream_147.iab -cA -s -r1 -o${output_path}Stream147_cA.json
${validator} -i${input_path}/IABValidationStream_148.iab -cA -s -r1 -o${output_path}Stream148_cA.json